apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stoiko-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "stoiko"
spec:
  backend:
    serviceName: stoiko-service
    servicePort: 80